/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube009_1: THREE.Mesh
    Cube009_2: THREE.Mesh
    Keyboard: THREE.Mesh
    Keyboard001: THREE.Mesh
    Keyboard002: THREE.Mesh
    Keyboard003: THREE.Mesh
    Keyboard004: THREE.Mesh
    Keyboard005: THREE.Mesh
    Keyboard006: THREE.Mesh
    Keyboard007: THREE.Mesh
    Keyboard008: THREE.Mesh
    Keyboard009: THREE.Mesh
    Keyboard010: THREE.Mesh
    Keyboard011: THREE.Mesh
    Keyboard012: THREE.Mesh
    Keyboard013: THREE.Mesh
    Keyboard014: THREE.Mesh
    Keyboard015: THREE.Mesh
    Keyboard016: THREE.Mesh
    Keyboard018: THREE.Mesh
    Keyboard019: THREE.Mesh
    Keyboard020: THREE.Mesh
    Keyboard021: THREE.Mesh
    Keyboard022: THREE.Mesh
    Keyboard023: THREE.Mesh
    Keyboard024: THREE.Mesh
    Keyboard025: THREE.Mesh
    Keyboard026: THREE.Mesh
    Keyboard027: THREE.Mesh
    Keyboard029: THREE.Mesh
    Keyboard030: THREE.Mesh
    Keyboard031: THREE.Mesh
    Keyboard032: THREE.Mesh
    Keyboard033: THREE.Mesh
    Keyboard034: THREE.Mesh
    Keyboard035: THREE.Mesh
    Keyboard036: THREE.Mesh
    Keyboard037: THREE.Mesh
    Keyboard038: THREE.Mesh
    Keyboard039: THREE.Mesh
    Keyboard040: THREE.Mesh
    Keyboard041: THREE.Mesh
    Keyboard043: THREE.Mesh
    Keyboard044: THREE.Mesh
    Keyboard046: THREE.Mesh
    Keyboard047: THREE.Mesh
    Keyboard048: THREE.Mesh
    Keyboard049: THREE.Mesh
    Keyboard050: THREE.Mesh
    Keyboard051: THREE.Mesh
    Keyboard052: THREE.Mesh
    Keyboard053: THREE.Mesh
    Keyboard054: THREE.Mesh
    Keyboard055: THREE.Mesh
    Keyboard058: THREE.Mesh
    Keyboard060: THREE.Mesh
    Keyboard061: THREE.Mesh
    Keyboard062: THREE.Mesh
    Keyboard063: THREE.Mesh
    Keyboard064: THREE.Mesh
    Keyboard065: THREE.Mesh
    Keyboard066: THREE.Mesh
    Keyboard067: THREE.Mesh
    Keyboard068: THREE.Mesh
    Keyboard069: THREE.Mesh
    Keyboard070: THREE.Mesh
    Keyboard071: THREE.Mesh
    Keyboard072: THREE.Mesh
    Keyboard073: THREE.Mesh
    Keyboard074: THREE.Mesh
    Keyboard075: THREE.Mesh
    Keyboard077: THREE.Mesh
    Keyboard079: THREE.Mesh
    Keyboard082: THREE.Mesh
    Keyboard099: THREE.Mesh
    Keyboard100: THREE.Mesh
    Keyboard101: THREE.Mesh
    Keyboard102: THREE.Mesh
    Keyboard103: THREE.Mesh
    Keyboard104: THREE.Mesh
    Keyboard028: THREE.Mesh
    Keyboard017: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube159: THREE.Mesh
    Cube159_1: THREE.Mesh
    Keycaps: THREE.Mesh
    Keycaps001: THREE.Mesh
    Keycaps002: THREE.Mesh
    Keycaps003: THREE.Mesh
    Keycaps004: THREE.Mesh
    Keycaps005: THREE.Mesh
    Keycaps006: THREE.Mesh
    Keycaps007: THREE.Mesh
    Keycaps008: THREE.Mesh
    Keycaps009: THREE.Mesh
    Keycaps010: THREE.Mesh
    Keycaps011: THREE.Mesh
    Keycaps012: THREE.Mesh
    Keycaps013: THREE.Mesh
    Keycaps014: THREE.Mesh
    Keycaps015: THREE.Mesh
    Keycaps016: THREE.Mesh
    Keycaps017: THREE.Mesh
    Keycaps018: THREE.Mesh
    Keycaps019: THREE.Mesh
    Keycaps020: THREE.Mesh
    Keycaps021: THREE.Mesh
    Keycaps022: THREE.Mesh
    Keycaps023: THREE.Mesh
    Keycaps024: THREE.Mesh
    Keycaps025: THREE.Mesh
    Keycaps026: THREE.Mesh
    Keycaps027: THREE.Mesh
    Keycaps028: THREE.Mesh
    Keycaps029: THREE.Mesh
    Keycaps030: THREE.Mesh
    Keycaps031: THREE.Mesh
    Keycaps032: THREE.Mesh
    Keycaps033: THREE.Mesh
    Keycaps034: THREE.Mesh
    Keycaps035: THREE.Mesh
    Keycaps036: THREE.Mesh
    Keycaps037: THREE.Mesh
    Keycaps038: THREE.Mesh
    Keycaps039: THREE.Mesh
    Keycaps040: THREE.Mesh
    Keycaps041: THREE.Mesh
    Keycaps042: THREE.Mesh
    Keycaps043: THREE.Mesh
    Keycaps044: THREE.Mesh
    Keycaps045: THREE.Mesh
    Keycaps046: THREE.Mesh
    Keycaps047: THREE.Mesh
    Keycaps048: THREE.Mesh
    Keycaps049: THREE.Mesh
    Keycaps050: THREE.Mesh
    Keycaps051: THREE.Mesh
    Keycaps053: THREE.Mesh
    Keycaps054: THREE.Mesh
    Keycaps055: THREE.Mesh
    Keycaps058: THREE.Mesh
    Keycaps059: THREE.Mesh
    Keycaps060: THREE.Mesh
    Keycaps061: THREE.Mesh
    Keycaps062: THREE.Mesh
    Keycaps063: THREE.Mesh
    Keycaps064: THREE.Mesh
    Keycaps065: THREE.Mesh
    Keycaps066: THREE.Mesh
    Keycaps067: THREE.Mesh
    Keycaps068: THREE.Mesh
    Keycaps069: THREE.Mesh
    Cube161: THREE.Mesh
    Cube161_1: THREE.Mesh
    Cube171: THREE.Mesh
    Cube171_1: THREE.Mesh
    Cube013: THREE.Mesh
    Cube015: THREE.Mesh
    Cylinder006: THREE.Mesh
    Cube167: THREE.Mesh
    Cube167_1: THREE.Mesh
    Cube167_2: THREE.Mesh
    Cube014: THREE.Mesh
    Cube016: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cube019: THREE.Mesh
    Cube011: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cube001: THREE.Mesh
    Cube004: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    LaptopScreen: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['keyboard light']: THREE.MeshStandardMaterial
    Monitor: THREE.MeshStandardMaterial
    ['Screen kiri']: THREE.MeshStandardMaterial
    ['Mainscreen.001']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Stand Monitor']: THREE.MeshStandardMaterial
    ['Backlight Monitor']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/personaldesk.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.001']}
        position={[-0.00569341, 1.35174775, -3.06808567]}
        rotation={[-2.60919205, -0.61298661, -2.8155176]}
        scale={[1.35725939, 0.03227554, 0.82406044]}
      />
      <group
        position={[-0.44598791, 2.43125701, -3.60663199]}
        rotation={[1.64634439, -0.06066604, 2.45951102]}
        scale={[1.35725939, 0.02838879, 0.78928673]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials.LaptopScreen}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard.geometry}
        material={nodes.Keyboard.material}
        position={[-0.2313762, 1.62093139, -3.54193878]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard001.geometry}
        material={nodes.Keyboard001.material}
        position={[-0.34549811, 1.6208353, -3.44882965]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard002.geometry}
        material={nodes.Keyboard002.material}
        position={[-0.45822802, 1.62074065, -3.35685802]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard003.geometry}
        material={nodes.Keyboard003.material}
        position={[-0.11864606, 1.62102604, -3.63391089]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard004.geometry}
        material={nodes.Keyboard004.material}
        position={[-0.00730804, 1.62111974, -3.72475004]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard005.geometry}
        material={nodes.Keyboard005.material}
        position={[-0.5681746, 1.62064815, -3.26715565]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard006.geometry}
        material={nodes.Keyboard006.material}
        position={[0.10542208, 1.62121439, -3.81672192]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard007.geometry}
        material={nodes.Keyboard007.material}
        position={[-0.67812109, 1.62055564, -3.17745352]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard008.geometry}
        material={nodes.Keyboard008.material}
        position={[0.2162036, 1.62130761, -3.90710449]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard009.geometry}
        material={nodes.Keyboard009.material}
        position={[-0.79085112, 1.62046099, -3.08547783]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard010.geometry}
        material={nodes.Keyboard010.material}
        position={[0.32976875, 1.62140322, -3.9997611]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard011.geometry}
        material={nodes.Keyboard011.material}
        position={[-0.90475023, 1.62036514, -2.99255133]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard012.geometry}
        material={nodes.Keyboard012.material}
        position={[0.44560489, 1.62150049, -4.09426832]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard013.geometry}
        material={nodes.Keyboard013.material}
        position={[-1.0177809, 1.62027001, -2.9003346]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard014.geometry}
        material={nodes.Keyboard014.material}
        position={[-0.94223046, 1.5657475, -2.80778909]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard015.geometry}
        material={nodes.Keyboard015.material}
        position={[0.46356556, 1.56692934, -3.95473719]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.13707297, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard016.geometry}
        material={nodes.Keyboard016.material}
        position={[-0.82919955, 1.56584263, -2.90000629]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard018.geometry}
        material={nodes.Keyboard018.material}
        position={[-0.71530032, 1.56593847, -2.99293256]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard019.geometry}
        material={nodes.Keyboard019.material}
        position={[0.29175434, 1.5667851, -3.81455922]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard020.geometry}
        material={nodes.Keyboard020.material}
        position={[-0.60257053, 1.56603312, -3.08490849]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard021.geometry}
        material={nodes.Keyboard021.material}
        position={[0.18097273, 1.56669188, -3.72417688]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard022.geometry}
        material={nodes.Keyboard022.material}
        position={[-0.49262407, 1.56612563, -3.17461061]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard023.geometry}
        material={nodes.Keyboard023.material}
        position={[0.06824291, 1.56659722, -3.63220477]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard024.geometry}
        material={nodes.Keyboard024.material}
        position={[-0.04309544, 1.56650352, -3.54136562]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard025.geometry}
        material={nodes.Keyboard025.material}
        position={[-0.38267747, 1.56621814, -3.26431251]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard026.geometry}
        material={nodes.Keyboard026.material}
        position={[-0.26994768, 1.56631279, -3.35628462]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard027.geometry}
        material={nodes.Keyboard027.material}
        position={[-0.15582559, 1.56640887, -3.44939375]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard029.geometry}
        material={nodes.Keyboard029.material}
        position={[0.6001873, 1.50474191, -3.8902204]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.07716925, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard030.geometry}
        material={nodes.Keyboard030.material}
        position={[-0.8023051, 1.50358057, -2.74601889]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard031.geometry}
        material={nodes.Keyboard031.material}
        position={[0.46815529, 1.50461841, -3.78246593]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard032.geometry}
        material={nodes.Keyboard032.material}
        position={[-0.68242598, 1.50367618, -2.84381008]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard033.geometry}
        material={nodes.Keyboard033.material}
        position={[0.35158724, 1.5045228, -3.68736887]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard034.geometry}
        material={nodes.Keyboard034.material}
        position={[-0.56371307, 1.50377107, -2.9406507]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard035.geometry}
        material={nodes.Keyboard035.material}
        position={[0.23480627, 1.50442958, -3.59210491]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard036.geometry}
        material={nodes.Keyboard036.material}
        position={[-0.44778094, 1.50386333, -3.03522158]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard037.geometry}
        material={nodes.Keyboard037.material}
        position={[0.119077, 1.50433493, -3.49769258]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard038.geometry}
        material={nodes.Keyboard038.material}
        position={[0.00474122, 1.50424147, -3.40441656]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard039.geometry}
        material={nodes.Keyboard039.material}
        position={[-0.33484045, 1.50395584, -3.12736011]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard040.geometry}
        material={nodes.Keyboard040.material}
        position={[-0.2221103, 1.50405073, -3.21933198]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard041.geometry}
        material={nodes.Keyboard041.material}
        position={[-0.10798869, 1.50414658, -3.31244087]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard043.geometry}
        material={nodes.Keyboard043.material}
        position={[0.65113866, 1.44046807, -3.75011921]}
        rotation={[-2.60919205, -0.61298661, -2.8155176]}
        scale={[0.12442227, 0.01108707, 0.06448732]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard044.geometry}
        material={nodes.Keyboard044.material}
        position={[-0.6903379, 1.43937111, -2.65573883]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard046.geometry}
        material={nodes.Keyboard046.material}
        position={[-0.57404363, 1.43946695, -2.75061226]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard047.geometry}
        material={nodes.Keyboard047.material}
        position={[0.48212317, 1.44031334, -3.61218929]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard048.geometry}
        material={nodes.Keyboard048.material}
        position={[-0.45404711, 1.43956161, -2.84849501]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard049.geometry}
        material={nodes.Keyboard049.material}
        position={[0.36146989, 1.44022036, -3.51377892]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard050.geometry}
        material={nodes.Keyboard050.material}
        position={[-0.33674964, 1.43965411, -2.9441781]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard051.geometry}
        material={nodes.Keyboard051.material}
        position={[0.24392787, 1.4401257, -3.41788912]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard052.geometry}
        material={nodes.Keyboard052.material}
        position={[0.12762871, 1.44003201, -3.32301521]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard053.geometry}
        material={nodes.Keyboard053.material}
        position={[-0.21944061, 1.43974662, -3.03986931]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard054.geometry}
        material={nodes.Keyboard054.material}
        position={[-0.10424772, 1.43984127, -3.13384628]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard055.geometry}
        material={nodes.Keyboard055.material}
        position={[0.00987464, 1.43993711, -3.22695518]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard058.geometry}
        material={nodes.Keyboard058.material}
        position={[-0.57841611, 1.37643552, -2.56901479]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard060.geometry}
        material={nodes.Keyboard060.material}
        position={[-0.46173099, 1.37653112, -2.66421127]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard061.geometry}
        material={nodes.Keyboard061.material}
        position={[0.69251513, 1.37737775, -3.60557604]}
        rotation={[-2.60919198, -0.6129865, -2.81551756]}
        scale={[0.19213246, 0.01108707, 0.06448798]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard062.geometry}
        material={nodes.Keyboard062.material}
        position={[-0.34901908, 1.37662601, -2.75616693]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard063.geometry}
        material={nodes.Keyboard063.material}
        position={[0.47560582, 1.37728453, -3.42885613]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard064.geometry}
        material={nodes.Keyboard064.material}
        position={[-0.23611614, 1.37671828, -2.84827614]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard065.geometry}
        material={nodes.Keyboard065.material}
        position={[0.35537991, 1.37718987, -3.33078671]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard066.geometry}
        material={nodes.Keyboard066.material}
        position={[0.23653293, 1.37709618, -3.2338419]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard067.geometry}
        material={nodes.Keyboard067.material}
        position={[-0.12022045, 1.37681079, -2.94281793]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard068.geometry}
        material={nodes.Keyboard068.material}
        position={[-0.00255838, 1.37690544, -3.03880358]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard069.geometry}
        material={nodes.Keyboard069.material}
        position={[0.11646482, 1.37700152, -3.1358974]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard070.geometry}
        material={nodes.Keyboard070.material}
        position={[-0.59176147, 1.31282473, -2.37848449]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard071.geometry}
        material={nodes.Keyboard071.material}
        position={[0.87162507, 1.31405497, -3.57241821]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard072.geometry}
        material={nodes.Keyboard072.material}
        position={[-0.47873053, 1.31291962, -2.47070146]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard073.geometry}
        material={nodes.Keyboard073.material}
        position={[0.6474067, 1.31386638, -3.38948679]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard074.geometry}
        material={nodes.Keyboard074.material}
        position={[-0.36483166, 1.31301546, -2.56363153]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard075.geometry}
        material={nodes.Keyboard075.material}
        position={[0.53477478, 1.31377172, -3.29759359]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard077.geometry}
        material={nodes.Keyboard077.material}
        position={[0.42399344, 1.31367874, -3.2072072]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard079.geometry}
        material={nodes.Keyboard079.material}
        position={[0.31126323, 1.31358385, -3.11523509]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard082.geometry}
        material={nodes.Keyboard082.material}
        position={[-0.02506062, 1.31330109, -2.84083819]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.33577493, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard099.geometry}
        material={nodes.Keyboard099.material}
        position={[-0.70694184, 1.31272793, -2.28451252]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard100.geometry}
        material={nodes.Keyboard100.material}
        position={[-0.74712062, 1.37628388, -2.43134928]}
        rotation={[-2.60919205, -0.61298661, -2.8155176]}
        scale={[0.12682946, 0.01108707, 0.06448733]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard101.geometry}
        material={nodes.Keyboard101.material}
        position={[-0.84618235, 1.43921947, -2.52852964]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.11552681, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard102.geometry}
        material={nodes.Keyboard102.material}
        position={[-0.94667578, 1.50343919, -2.62817478]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.09710605, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard103.geometry}
        material={nodes.Keyboard103.material}
        position={[-1.05741096, 1.5656507, -2.71381712]}
        rotation={[-2.60919206, -0.61298641, -2.81551764]}
        scale={[0.06393101, 0.01108707, 0.06448735]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard104.geometry}
        material={nodes.Keyboard104.material}
        position={[-1.13296151, 1.62017322, -2.80636239]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.04283169]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard028.geometry}
        material={nodes.Keyboard028.material}
        position={[0.78084028, 1.29967546, -3.45794725]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.03174005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard017.geometry}
        material={nodes.Keyboard017.material}
        position={[0.73877215, 1.33003449, -3.50948095]}
        rotation={[-2.60919206, -0.61298648, -2.81551763]}
        scale={[0.06393101, 0.01108707, 0.03174005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Material.001']}
        position={[0, 0.0079906, 0.70600843]}
        scale={[2.23002219, 0.1425364, 7.1327076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials['Material.006']}
        position={[0, -2.56989908, 6.82380676]}
        scale={[2.06991029, 2.42766571, 0.2897642]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials['Material.006']}
        position={[0, -2.56989908, -5.67618561]}
        scale={[2.06991029, 2.42766571, 0.2897642]}
      />
      <group
        position={[0.47298038, 0.17096552, 1.36069596]}
        rotation={[Math.PI, -0.00056442, Math.PI]}
        scale={[0.34276384, 0.0201139, 0.92924339]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube159.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube159_1.geometry}
          material={materials['keyboard light']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps.geometry}
        material={nodes.Keycaps.material}
        position={[0.25289571, 0.20750409, 1.87955391]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps001.geometry}
        material={nodes.Keycaps001.material}
        position={[0.25265265, 0.20750409, 1.77089036]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps002.geometry}
        material={nodes.Keycaps002.material}
        position={[0.25240958, 0.20750409, 1.6622268]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps003.geometry}
        material={nodes.Keycaps003.material}
        position={[0.25216639, 0.20750409, 1.55356324]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps004.geometry}
        material={nodes.Keycaps004.material}
        position={[0.25313354, 0.20750409, 1.98585427]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps005.geometry}
        material={nodes.Keycaps005.material}
        position={[0.25339043, 0.20750409, 2.10065937]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps006.geometry}
        material={nodes.Keycaps006.material}
        position={[0.25362515, 0.20750409, 2.20554256]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps007.geometry}
        material={nodes.Keycaps007.material}
        position={[0.25191271, 0.20750409, 1.44017708]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps008.geometry}
        material={nodes.Keycaps008.material}
        position={[0.25167799, 0.20750409, 1.33529389]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps009.geometry}
        material={nodes.Keycaps009.material}
        position={[0.25143385, 0.20750409, 1.22615731]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps010.geometry}
        material={nodes.Keycaps010.material}
        position={[0.25118661, 0.20750409, 1.11560547]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps011.geometry}
        material={nodes.Keycaps011.material}
        position={[0.25094235, 0.20750409, 1.00647092]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps012.geometry}
        material={nodes.Keycaps012.material}
        position={[0.25069821, 0.20750409, 0.89733618]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps013.geometry}
        material={nodes.Keycaps013.material}
        position={[0.34695375, 0.20750409, 0.84184378]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps014.geometry}
        material={nodes.Keycaps014.material}
        position={[0.34719801, 0.20750409, 0.95097846]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps015.geometry}
        material={nodes.Keycaps015.material}
        position={[0.34744215, 0.20750409, 1.06011319]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps016.geometry}
        material={nodes.Keycaps016.material}
        position={[0.34768951, 0.20750409, 1.17066681]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps017.geometry}
        material={nodes.Keycaps017.material}
        position={[0.34793365, 0.20750409, 1.27980149]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps018.geometry}
        material={nodes.Keycaps018.material}
        position={[0.34816837, 0.20750409, 1.38468468]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps019.geometry}
        material={nodes.Keycaps019.material}
        position={[0.34666014, 0.20750409, 0.71058005]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.05475479, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps020.geometry}
        material={nodes.Keycaps020.material}
        position={[0.34964609, 0.20750409, 2.04516697]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps021.geometry}
        material={nodes.Keycaps021.material}
        position={[0.3493892, 0.20750409, 1.93036187]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps022.geometry}
        material={nodes.Keycaps022.material}
        position={[0.34842205, 0.20750409, 1.49807274]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps023.geometry}
        material={nodes.Keycaps023.material}
        position={[0.34866524, 0.20750409, 1.6067344]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps024.geometry}
        material={nodes.Keycaps024.material}
        position={[0.34890831, 0.20750409, 1.71539795]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps025.geometry}
        material={nodes.Keycaps025.material}
        position={[0.34915149, 0.20750409, 1.82406151]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps026.geometry}
        material={nodes.Keycaps026.material}
        position={[0.46247864, 0.20460933, 1.79687798]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps027.geometry}
        material={nodes.Keycaps027.material}
        position={[0.46223545, 0.20460933, 1.68821442]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps028.geometry}
        material={nodes.Keycaps028.material}
        position={[0.46199238, 0.20460933, 1.57955277]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps029.geometry}
        material={nodes.Keycaps029.material}
        position={[0.4617492, 0.20460933, 1.47088921]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps030.geometry}
        material={nodes.Keycaps030.material}
        position={[0.46271646, 0.20460933, 1.90317833]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps031.geometry}
        material={nodes.Keycaps031.material}
        position={[0.46297336, 0.20460933, 2.01798344]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps032.geometry}
        material={nodes.Keycaps032.material}
        position={[0.46328747, 0.20460933, 2.15839672]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.0613721, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps033.geometry}
        material={nodes.Keycaps033.material}
        position={[0.46149564, 0.20460933, 1.35750115]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps034.geometry}
        material={nodes.Keycaps034.material}
        position={[0.46126091, 0.20460933, 1.25261796]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps035.geometry}
        material={nodes.Keycaps035.material}
        position={[0.46101665, 0.20460933, 1.14348328]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps036.geometry}
        material={nodes.Keycaps036.material}
        position={[0.4607693, 0.20460933, 1.03292966]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps037.geometry}
        material={nodes.Keycaps037.material}
        position={[0.46052516, 0.20460933, 0.92379493]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps038.geometry}
        material={nodes.Keycaps038.material}
        position={[0.46011996, 0.20460933, 0.74269217]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.08761555, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps039.geometry}
        material={nodes.Keycaps039.material}
        position={[0.58651161, 0.20113564, 0.65487403]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps040.geometry}
        material={nodes.Keycaps040.material}
        position={[0.56518662, 0.20113564, 0.82437247]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.07159241, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps041.geometry}
        material={nodes.Keycaps041.material}
        position={[0.56552589, 0.20113564, 0.97600287]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps042.geometry}
        material={nodes.Keycaps042.material}
        position={[0.56577325, 0.20113564, 1.08655274]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps043.geometry}
        material={nodes.Keycaps043.material}
        position={[0.56601739, 0.20113564, 1.19568932]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps044.geometry}
        material={nodes.Keycaps044.material}
        position={[0.56625211, 0.20113564, 1.30057251]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps045.geometry}
        material={nodes.Keycaps045.material}
        position={[0.56811535, 0.20113564, 2.13333607]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.08355061, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps046.geometry}
        material={nodes.Keycaps046.material}
        position={[0.56772983, 0.20113564, 1.96105492]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps047.geometry}
        material={nodes.Keycaps047.material}
        position={[0.56747293, 0.20113564, 1.8462497]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps048.geometry}
        material={nodes.Keycaps048.material}
        position={[0.56650579, 0.20113564, 1.41396058]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps049.geometry}
        material={nodes.Keycaps049.material}
        position={[0.56674886, 0.20113564, 1.52262414]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps050.geometry}
        material={nodes.Keycaps050.material}
        position={[0.56699204, 0.20113564, 1.63128579]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps051.geometry}
        material={nodes.Keycaps051.material}
        position={[0.56723511, 0.20113564, 1.73994935]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps053.geometry}
        material={nodes.Keycaps053.material}
        position={[0.22997892, 0.20750409, 0.52538413]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps054.geometry}
        material={nodes.Keycaps054.material}
        position={[0.68273103, 0.19939879, 2.04859257]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps055.geometry}
        material={nodes.Keycaps055.material}
        position={[0.68242049, 0.19939879, 1.90977204]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps058.geometry}
        material={nodes.Keycaps058.material}
        position={[0.68303895, 0.19939879, 2.18615627]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps059.geometry}
        material={nodes.Keycaps059.material}
        position={[0.3503238, 0.20750409, 0.52092475]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps060.geometry}
        material={nodes.Keycaps060.material}
        position={[0.68152428, 0.19939879, 1.50918686]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.24585083, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps061.geometry}
        material={nodes.Keycaps061.material}
        position={[0.4682368, 0.20460933, 0.52515525]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps062.geometry}
        material={nodes.Keycaps062.material}
        position={[0.68060029, 0.19939879, 1.09621918]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps063.geometry}
        material={nodes.Keycaps063.material}
        position={[0.68035614, 0.19939879, 0.98708457]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps064.geometry}
        material={nodes.Keycaps064.material}
        position={[0.68011189, 0.19939879, 0.87794989]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps065.geometry}
        material={nodes.Keycaps065.material}
        position={[0.35023379, 0.20750409, 2.17464352]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.05287401, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps066.geometry}
        material={nodes.Keycaps066.material}
        position={[0.24419391, 0.20750409, 0.73061103]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.07557196, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps067.geometry}
        material={nodes.Keycaps067.material}
        position={[0.7016573, 0.19939879, 0.65461463]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps068.geometry}
        material={nodes.Keycaps068.material}
        position={[0.70141494, 0.19939879, 0.546323]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keycaps069.geometry}
        material={nodes.Keycaps069.material}
        position={[0.70190251, 0.19939879, 0.76427954]}
        rotation={[-Math.PI, 1.56861388, -Math.PI]}
        scale={[0.03765281, 0.01687687, 0.03945228]}
      />
      <group
        position={[0.18933403, 2.97455883, 3.73755431]}
        rotation={[-1.57140141, -0.00065487, 0.82508917]}
        scale={[0.07364812, 1.23433363, 2.11746693]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube161.geometry}
          material={materials.Monitor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube161_1.geometry}
          material={materials['Screen kiri']}
        />
      </group>
      <group
        position={[-0.89068979, 2.00278068, 0.66605622]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.07235026, -1.17273772, -2.21972847]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube171.geometry}
          material={materials.Monitor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube171_1.geometry}
          material={materials['Mainscreen.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials['Material.004']}
        position={[-2.14327621, 0.04744537, 0.70703501]}
        scale={[0.419168, 0.42240128, 0.37999904]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials['Stand Monitor']}
        position={[-1.75561607, 2.03492451, 0.69488311]}
        rotation={[0, 0, -1.56541867]}
        scale={[0.15240043, 0.77378172, 0.23550153]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials['Stand Monitor']}
        position={[-2.08551979, 1.60433185, 0.69574076]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.18364877, -1.54106224, -0.1818191]}
      />
      <group
        position={[-1.00524426, 2.04360533, 0.67475307]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.04287164, -0.65926498, -0.6839512]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167.geometry}
          material={materials['Stand Monitor']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167_1.geometry}
          material={materials['Backlight Monitor']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167_2.geometry}
          material={materials.Monitor}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials['Stand Monitor']}
        position={[0.11494496, 2.81857586, 3.89502788]}
        rotation={[0.00674334, 0.82423611, -1e-8]}
        scale={[0.04476615, 0.47921187, 0.64188844]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials['Material.004']}
        position={[-0.49975163, 0.15328801, 3.94161844]}
        scale={[0.08015203, 0.13128354, 0.73213041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials['Stand Monitor']}
        position={[-0.49712211, 1.71483684, 4.57654572]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.18364875, -1.56064391, -0.1818191]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials['Stand Monitor']}
        position={[-0.22254637, 2.80075312, 4.26138687]}
        rotation={[-Math.PI, 0.70560012, -Math.PI]}
        scale={[0.03765361, 0.25067896, 0.45806569]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials['Material.005']}
        position={[0.256055, 0.15328801, 4.58348417]}
        rotation={[Math.PI, -1.56921144, Math.PI]}
        scale={[0.08015202, 0.13128354, 0.73213041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Material.004']}
        position={[-0.3546364, 0.76690471, -2.97688818]}
        rotation={[-3e-8, -0.88788037, -0.42530269]}
        scale={[0.06931998, 0.44340369, 0.01920031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Material.004']}
        position={[0.12158406, 0.76690471, -3.36428881]}
        rotation={[-3e-8, -0.88788037, -0.42530269]}
        scale={[0.06931998, 0.44340369, 0.01920031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.004']}
        position={[-0.47359553, 0.33915877, -3.12312078]}
        rotation={[-1.2236787, 0.2513394, -0.93541231]}
        scale={[0.08852605, 0.03873044, 0.09838805]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.004']}
        position={[-0.23434457, 1.17412043, -2.82901716]}
        rotation={[-1.2236787, 0.2513394, -0.93541231]}
        scale={[0.08852605, 0.03873044, 0.09838805]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.004']}
        position={[0.24187586, 1.17412043, -3.21641803]}
        rotation={[-1.2236787, 0.2513394, -0.93541231]}
        scale={[0.08852605, 0.03873044, 0.09838805]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.004']}
        position={[0.00262493, 0.33915877, -3.51052165]}
        rotation={[-1.2236787, 0.2513394, -0.93541231]}
        scale={[0.08852605, 0.03873044, 0.09838805]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[0.20610622, 0.97207731, -2.29373384]}
        rotation={[0.53248155, 0.61130777, -0.32612111]}
        scale={[1, 0.30544269, 0.52281141]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[0.75323772, 0.97207731, -2.73882389]}
        rotation={[0.53248155, 0.61130777, -0.32612111]}
        scale={[1, 0.30544269, 0.52281141]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials['Material.004']}
        position={[-0.12397799, 0.73782647, -3.18010378]}
        rotation={[0.53536634, 0.61623041, -1.89934125]}
        scale={[0.09088752, 0.32919773, 0.04166341]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.004']}
        position={[0.05409786, 0.19040394, -2.96120143]}
        rotation={[0, -0.88788021, 0]}
        scale={[1, 0.05899674, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['Material.004']}
        position={[-0.00024015, 1.27959347, -3.02799702]}
        rotation={[2e-8, -0.88788048, -0.42161422]}
        scale={[0.76570708, 0.00613428, 0.65636885]}
      />
    </group>
  )
}

useGLTF.preload('/personaldesk.glb')
